// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrTjv3nF-CGyuSXFMI7gLJMH5qJn9ZlAI',
    appId: '1:664180170783:web:2ed2230fb1ce15dbc1f52a',
    messagingSenderId: '664180170783',
    projectId: 'learning-flutter-57e6f',
    authDomain: 'learning-flutter-57e6f.firebaseapp.com',
    storageBucket: 'learning-flutter-57e6f.appspot.com',
    measurementId: 'G-N104BC8430',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAceJQ0X57ZW8W7-bR9hyfBlA5m51ILBcI',
    appId: '1:664180170783:android:2796ab1a4291e1f0c1f52a',
    messagingSenderId: '664180170783',
    projectId: 'learning-flutter-57e6f',
    storageBucket: 'learning-flutter-57e6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhaTfTRh_oPKjZy-zpLuCUTHqgpKpSubw',
    appId: '1:664180170783:ios:4d019e486a49dda0c1f52a',
    messagingSenderId: '664180170783',
    projectId: 'learning-flutter-57e6f',
    storageBucket: 'learning-flutter-57e6f.appspot.com',
    iosClientId: '664180170783-hor2j1ve1uf89n9tpr5l8cf4fe761iga.apps.googleusercontent.com',
    iosBundleId: 'learningflutter',
  );
}
